[package]
name = "build_wasmtime"
version = "0.1.0"
authors = ["Evan Johnson <e5johnso@eng.ucsd.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
